### ISSUE TITLE
Error in train.txt for NER dataset

### ISSUE THREAD

**Issue by AnakTeka** [grit-id/nergrit-corpus#1]
Hello, thanks for the dataset, but there are few small errors in train.txt.

These lines have wrong format for IOB1

```
24229
44085
64169
74138
```

in test.txt:

```
35178
60734
```
For example on line number 24229 from train.txt:

![image](https://user-images.githubusercontent.com/3157407/63583161-a8564a00-c5c4-11e9-8c20-d1553f5b12a4.png)

There should not be a space and followed by O on IOB1 tag.

and also on line 64169 from train.txt there is a trailling comma left behind
![image](https://user-images.githubusercontent.com/3157407/63583684-b062b980-c5c5-11e9-99a9-a18f2fca8ac4.png)

There are also inconsistency that used to encode non entity token, many words was encoded as 0 **Zero** instead of capital O
```
Jokowi  B-PER    
Bakal   0        
Rilis   0        
Paket   0        
Kebijakan   O    
Cegah   O        
Korupsi O
```

There are also a few wrong labels on token, is there any documentation for 19 entities and their encoded label? For example Person as PER, Organization as ORG, Location as LOC. Because I have found that there are few labels that was not actually part of that 19 entities, as seen below.

This was taken from train.txt

```
{'O': 225068,
 'I-DAT': 9918,
 'B-PER': 6750,
 'B-GPE': 6544,
 'I-NOR': 5547,
 'I-ORG': 5445,
 'I-LOC': 4601,
 'I-PER': 4410,
 'B-ORG': 4306,
 'I-PRD': 4223,
 'B-PRD': 4158,
 'B-NOR': 3905,
 'B-DAT': 3605,
 'B-CRD': 3425,
 'I-MON': 3272,
 'B-LOC': 2853,
 'I-TIM': 2811,
 'I-QTY': 2451,
 'I-EVT': 2435,
 'I-GPE': 2344,
 'B-QTY': 1505,
 'I-PRC': 1485,
 'B-EVT': 1408,
 'I-CRD': 1404,
 'I-LAW': 1354,
 'B-MON': 1292,
 'I-FAC': 927,
 'B-TIM': 812,
 'B-PRC': 743,
 'B-ORD': 570,
 'B-FAC': 480,
 'I-WOA': 368,
 'B-REG': 361,
 'B-LAW': 314,
 'B-WOA': 196,
 'I-REG': 177,
 'o': 43,
 'I-ORD': 41,
 '0': 19,
 'I': 14,
 'B-LAN': 12,
 'I-LAN': 11,
 ' O': 10,
 'P': 7,
 'I-DAI': 6,
 'I-DaT': 6,
 'I-OC': 5,
 'I-PR': 4,
 'CRD': 3,
 'I-TOL': 3,
 'O‚Äé': 3,
 'B-L0C': 3,
 'B-PR': 3,
 'B-QYT': 3,
 'I-QYT': 3,
 'I-FA': 3,
 'B-PROD': 2,
 'I-BTN': 2,
 'B-O': 2,
 'I-EVE': 2,
 'O`': 2,
 'I-0RG': 2,
 'B-BAT': 2,
 'B-EVT`': 2,
 'BWOA': 2,
 'B-BGPE': 2,
 'B=PER': 2,
 'I-NOE': 2,
 'OB-PRD': 2,
 'I-RG': 1,
 'B=CRD': 1,
 'B-PRG': 1,
 'ORD': 1,
 'B-EVE': 1,
 'DAT': 1,
 'B-PER.': 1,
 'I-TO;': 1,
 'B=PRD': 1,
 'N-NOR': 1,
 'B-NOE': 1,
 'i-FAC': 1,
 'B': 1,
 'I-[OC': 1,
 'B-CRR': 1,
 'I-PD': 1,
 'B-FA': 1,
 'I-AC': 1,
 'B-OR': 1,
 'B-ER': 1,
 'IDAT': 1,
 'B-ODR': 1,
 '`O': 1,
 'b-org': 1,
 'B-QT': 1,
 'QTY': 1,
 'O-RG': 1,
 'O-PRD': 1,
 'B-CTY': 1,
 'I-TY': 1,
 'I-M0N': 1,
 'IMON': 1,
 'I=EVT': 1,
 'B-M0N': 1,
 'BPER': 1,
 'B-N0R': 1,
 'PO': 1,
 'B-PGE': 1,
 'B=GPE': 1,
 'I-ORH': 1,
 'IO': 1,
 'BGPE': 1,
 'N-GPE': 1,
 'I=ORG': 1,
 'B-PE': 1,
 'B-NPR': 1,
 'GPE': 1,
 'NOR': 1,
 'd': 1,
 'I-OR': 1,
 'O -': 1,
 '9': 1,
 'BPRD': 1,
 '8': 1,
 'B-WTY': 1,
 'I-RD': 1,
 'I-DAR': 1,
 '6': 1}
```

**Comment by aviezab** [comment]
@AnakTeka Hello Mas Yoga, Thanks for feedback, We will follow up this issue soon, or Mas Yoga could give the fixed one, and We will include Mas Yoga for contributors. Please inform notice me here.

**Comment by AnakTeka** [comment]
Sorry If didn't make myself clear, what I meant by documentation of the entities is as stated here https://ner.grit.id/index.php/front/ner there are 19 entities on this dataset, meanwhile I found only 18 labels, this is after fixed the train.txt

```
{'CRD',
 'DAT',
 'EVT',
 'FAC',
 'GPE',
 'LAW',
 'LOC',
 'MON',
 'NOR',
 'ORD',
 'ORG',
 'PER',
 'PRC',
 'PRD',
 'QTY',
 'REG',
 'TIM',
 'WOA'}
```

It would be great if we could now what is CRD, DAT, EVT, FAC, GPE, LAW maps to.
CRD -> ?
DAT -> ?
EVT -> ?

and this is the count for each tags after fixing, ignore the `''`, it is a count how many sample that we have.
```
{'O': 213827,
 '': 12551,
 'I-DAT': 9906,
 'B-PER': 6721,
 'B-GPE': 6453,
 'I-NOR': 5544,
 'I-ORG': 5426,
 'I-LOC': 4529,
 'I-PER': 4359,
 'I-PRD': 4181,
 'B-ORG': 4173,
 'B-PRD': 4140,
 'B-NOR': 3895,
 'B-DAT': 3588,
 'B-CRD': 3427,
 'I-MON': 3251,
 'B-LOC': 2844,
 'I-QTY': 2446,
 'I-EVT': 2387,
 'I-TIM': 2360,
 'I-GPE': 2315,
 'B-QTY': 1510,
 'I-PRC': 1472,
 'B-EVT': 1400,
 'I-CRD': 1395,
 'I-LAW': 1350,
 'B-MON': 1292,
 'I-FAC': 929,
 'B-TIM': 811,
 'B-PRC': 745,
 'B-ORD': 572,
 'B-FAC': 481,
 'I-WOA': 368,
 'B-REG': 356,
 'B-LAW': 314,
 'B-WOA': 195,
 'I-REG': 176,
 'I-ORD': 41,
 'B-LAN': 12,
 'I-LAN': 11}
```

I could upload the fixed train.txt, valid.txt, and test.txt in case needed.

**Comment by aviezab** [comment]
@AnakTeka Yes, You are right. When We started the development, the engine is able to recognize 19 entities. After a year building corpus, We just realized the data We have is only consisting 18 entities, although the engine is able to recognize 19 entities.

For now, I will example the entities here. Later We will include it in the zip file.

```
{'CRD', --> Cardinal
 'DAT', --> Date
 'EVT', --> Event
 'FAC', --> Facility
 'GPE', --> Geopolitical Entity
 'LAW', --> Law Entity (such as Undang-Undang)
 'LOC', --> Location
 'MON', --> Money
 'NOR', --> Political Organization
 'ORD', --> Ordinal
 'ORG', --> Organization
 'PER', --> Person
 'PRC', --> Percent
 'PRD', --> Product
 'QTY', --> Quantity
 'REG', --> Religion
 'TIM', --> Time
 'WOA' --> Work of Art
}
```
The missing entity is `LAN --> Language`.

Of course, You can send us the fixed data-set. Please send it to contact@grit.id , Thank You.

**Comment by aviezab** [comment]
@AnakTeka Hello Mas Yoga, I am going to close this issue soon, have You sent the better dataset? Thanks.

**Comment by aviezab** [comment]
This issue closed. New dataset updated at NERGRIT.
Thanks @AnakTeka and Abdul Hamid.

**Comment by cahya-wirawan** [comment]
Hi @aviezab 
Thanks for the dataset. For your information,  It seems that the NER dataset I received in August 2020 still has so many typos on the tags/labels. Following is the mapping list that I used to correct the labels in the train.txt,valid.txt and test.txt. The first column is the typo, the second column is the correction. Yes, it is a long list.

```
0 O
6 O
8 O
9 O
B O
B-BAT B-DAT
B-BGPE B-GPE
B=CRD B-CRD
B-CRD B-CRD
B-CRR B-CRD
B-CTY B-CRD
B-DAT B-DAT
B-ER B-PER
B-EVE B-EVE
B-EVT B-EVE
B-EVT` B-EVE
B-FA B-FAC
B-FAC B-FAC
BGPE B-GPE
B=GPE B-GPE
B-GPE B-GPE
B-L0C B-LOC
B-LAN B-LAN
B-LAW B-LAW
B-LOC B-LOC
B-M0N B-MON
B-MON B-MON
B-N0R B-NOR
B-NOE B-NOR
B-NOR B-NOR
B-NPR B-NOR
B-O O
B-ODR B-ORD
B-OR B-ORG
B-ORD B-ORD
b-org B-ORG
B-ORG B-ORG
B-PE B-PER
BPER B-PER
B=PER B-PER
B-PER B-PER
B-PER. B-PER
B-PGE B-GPE
B-PR B-PRC
B-PRC B-PRC
BPRD B-PRD
B=PRD B-PRD
B-PRD B-PRD
B-PRG B-PRD
B-PROD B-PRD
B-QT B-QTY
B-QTY B-QTY
B-QYT B-QTY
B-REG B-REG
B-TIM B-TIM
BWOA B-WOA
B-WOA B-WOA
B-WTY B-QTY
CRD B-CRD
d O
DAT B-DAT
GPE B-GPE
I O
I-0RG I-ORG
I-AC I-FAC
I-BTN I-ORG
I-CRD I-CRD
I-DAI I-DAT
I-DAR I-DAT
I-DaT I-DAT
IDAT I-DAT
I-DAT I-DAT
I-EVE I-EVE
I=EVT I-EVE
I-EVT I-EVE
I-FA I-FAC
i-FAC I-FAC
I-FAC I-FAC
I-GPE I-GPE
I-LAN I-LAN
I-LAW I-LAW
I-LOC I-LOC
I-M0N I-MON
IMON I-MON
I-MON I-MON
I-NOE I-NOR
I-NOR I-NOR
IO O
I-OC I-LOC
I-[OC I-LOC
I-OR I-NOR
I-ORD I-ORD
I=ORG I-ORG
I-ORG I-ORG
I-ORH I-ORG
I-PD I-PRD
I-PER I-PER
I-PR I-PRD
I-PRC I-PRC
I-PRD I-PRD
I-QTY I-QTY
I-QYT I-QTY
I-RD I-PRD
I-REG I-REG
I-RG I-ORG
I-TIM I-TIM
I-TO; I-FAC
I-TOL I-FAC
I-TY I-QTY
I-WOA I-WOA
N-GPE B-GPE
N-NOR B-NOR
NOR I-NOR
o O
O O
`O O
O` O
O- O
O, O
OB-PRD B-PRD
O-PRD I-PRD
ORD B-ORD
O-RG I-ORG
P O
PO O
QTY I-QTY
```

**Comment by cahya-wirawan** [comment]
I am just wondering how was the dataset labeled, why there are so many errors on the label. Maybe you need a proper software for the data annotation, such as Doccano.

**Comment by cahya-wirawan** [comment]
Hi @aviezab, I just sent to  contact@grit.id the corrected ner dataset files.

**Comment by aviezab** [comment]
Halo Pak @cahya-wirawan 
Thanks for correction,

> I am just wondering how was the dataset labeled, why there are so many errors on the label. Maybe you need a proper software for the data annotation, such as Doccano.
There are so many people doing tagging with culture of "deadline-software-house", so We decided to ask permit to make this corpus open source, so people can help us fixing the data annotation.

Anyway thank You for the information and the contribution, I will include You to the contributors list.
